#!/bin/bash

# Magic to get where this script lives
HERE=$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/)


# 3-finger claw
shout() { echo "$0: $*" >&2; }  # Just echo an error and the program name
barf() { shout "$*"; exit 111; }
safe() { "$@" || barf "cannot $*"; }

safe cd "$HERE"

deactivate 2> /dev/null

source bin/activate || barf "No virtualenv in $HERE??"

# Update TAGS file
ctags -e -R . 2>/dev/null


verify_executables() {
    MISSING=0
    for executable in "$@"; do
        which $executable > /dev/null
        if [ $? -ne 0 ]; then
            shout "Could not find: $executable"
            MISSING=$(($MISSING + 1))
        fi
    done
    if [ $MISSING -gt 0 ]; then
        barf "Install missing dependencies above"
    fi
}

verify_executables mypy coverage dart

echo Type check...
mypy -p lox
STATUS=$?

mypy lox.py lox_*.py
STATUS=$(($? + $STATUS))

rm -rf .coverage

echo Python tests...
coverage run -m unittest -v python_tests/test*py
STATUS=$(($? + $STATUS))
echo
echo Dart tests...
# Hack: retrofit custom output to make the ch4 tests happy

echo "Chapter 4..."
# Dart is a bit odd in that it requires prefacing EACH arg to the intepreter with '-a'.
# So the actual command dart is running is like eg "bin/coverage run --append ./loc_ch4.py test/scanning/keywords.lox"
dart test/test.dart chap04_scanning --interpreter ./bin/coverage -a run -a --append -a ./lox_ch4.py
STATUS=$(($? + $STATUS))

echo "Chapter 6..."
dart test/test.dart chap06_parsing --interpreter  ./bin/coverage -a run -a --append -a ./lox_ch6.py
STATUS=$(($? + $STATUS))

echo "Chapter 7..."
dart test/test.dart chap07_evaluating --interpreter ./bin/coverage -a run -a --append -a ./lox_ch7.py
STATUS=$(($? + $STATUS))

echo "Chapter 8..."
dart test/test.dart chap08_statements --interpreter ./bin/coverage -a run -a --append -a ./lox_ch8.py
STATUS=$(($? + $STATUS))

echo "Chapter 9..."
dart test/test.dart chap09_control --interpreter ./bin/coverage -a run -a --append -a ./lox_ch9.py
STATUS=$(($? + $STATUS))

echo "Chapter 10..."
dart test/test.dart chap10_functions --interpreter ./bin/coverage -a run -a --append -a ./lox_ch10.py
STATUS=$(($? + $STATUS))

echo "Chapter 11..."
dart test/test.dart chap11_resolving --interpreter ./bin/coverage -a run -a --append -a ./lox_ch11.py
STATUS=$(($? + $STATUS))

echo "Chapter 12..."
dart test/test.dart chap12_classes --interpreter ./bin/coverage -a run -a --append -a ./lox.py
STATUS=$(($? + $STATUS))

echo Coverage report...
coverage report -m
echo

if [ "$STATUS" -ne "0" ]; then
    shout "One or more steps reported failure."
else
    echo All passed
fi
exit $STATUS
